# Generated by Django 5.0.6 on 2024-06-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wear',
            name='pic',
            field=models.ImageField(blank=True, upload_to='myapp/static/img'),
        ),
        migrations.AlterField(
            model_name='wear',
            name='cost',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='wear',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='wear',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='wear',
            name='dod',
            field=models.DateField(auto_now=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='wear',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='wear',
            name='size',
            field=models.CharField(max_length=10, verbose_name='Размер'),
        ),
    ]
